spring.datasource.url=jdbc:postgresql://dpg-d6kjue56ubrc73ehst8g-a/mysqldb_vkt9
spring.datasource.username=mysqldb_vkt9_user
spring.datasource.password=eOLsTJpHqKcvteS5YPSPjWgnQfUUAwKo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}